import { randomBytes } from 'node:crypto';
import express from 'express';
import { join } from 'node:path';
import { config, ROOT } from './config.ts';
import { openRepo } from './repo/index.ts';
import { catalogueRoutes } from './routes/catalogue.ts';
import { orderRoutes } from './routes/orders.ts';
import { analyticsRoutes } from './routes/analytics.ts';
import { adminRoutes } from './routes/admin.ts';
import { reviewRoutes } from './routes/reviews.ts';
import { HttpError } from './lib/http.ts';
import { business, unfilled } from './lib/business.ts';
import { demoData, refuseDemoDataInProduction } from './lib/demo-data.ts';
import { homeShare, origin, productShare, renderPage } from './lib/share.ts';
import { rate, reviews } from './lib/reviews.ts';

refuseDemoDataInProduction();

const repo = await openRepo(config.driver, ROOT);
const app = express();

app.use(express.json({ limit: '256kb' }));

/*
 * Two pages are rendered rather than served, so their <head> can carry a share
 * card and structured data. Everything WhatsApp, Instagram, Facebook and Google
 * need is read out of the HTML as it arrives — none of them run the JavaScript
 * that draws the rest of the page. Registered before the static directory, or
 * the plain file wins.
 */
const shared = async (req: express.Request, res: express.Response, next: express.NextFunction) => {
  try {
    const path = req.path === '/' ? '/index.html' : req.path;
    if (path === '/index.html') {
      res.type('html').send(renderPage('index.html', homeShare(req)));
      return;
    }
    if (path === '/product.html') {
      const slug = typeof req.query.slug === 'string' ? req.query.slug : '';
      const product = slug ? await repo.getProduct(slug) : null;
      if (!product || product.status !== 'active') {
        /*
         * A 404, not the shell with a 200. Falling through served the page
         * frame for a piece that is not live — a soft 404 that a search engine
         * indexes and a customer reads as a broken site rather than a gone one.
         */
        res.status(404).type('html').sendFile(join(ROOT, 'public', '404.html'));
        return;
      }
      const rating = rate(await reviews().forProduct(product.slug).catch(() => []));
      res.type('html').send(renderPage('product.html', productShare(product, req, rating)));
      return;
    }
    next();
  } catch {
    // A share card is never a reason to fail a page.
    next();
  }
};
app.get(['/', '/index.html', '/product.html'], (req, res, next) => { void shared(req, res, next); });

/**
 * Every live piece, for search engines. Generated rather than kept as a file:
 * a sitemap that has to be regenerated by hand is a sitemap that is wrong.
 */
app.get('/sitemap.xml', (req, res) => {
  void (async () => {
    const base = origin(req);
    const page = await repo.listProducts({ perPage: 100 });
    const urls = [
      { loc: `${base}/`, pri: '1.0' },
      ...(await repo.listCategories()).map((c) => ({
        loc: `${base}/?category=${encodeURIComponent(c.slug)}`, pri: '0.7',
      })),
      ...page.items.map((p) => ({
        loc: `${base}/product.html?slug=${encodeURIComponent(p.slug)}`,
        pri: '0.8',
        lastmod: p.updatedAt.slice(0, 10),
      })),
      { loc: `${base}/contact.html`, pri: '0.3' },
      { loc: `${base}/privacy.html`, pri: '0.3' },
    ];
    res.type('application/xml').send(
      `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n`
      + urls.map((u) => `  <url><loc>${u.loc.replace(/&/g, '&amp;')}</loc>`
        + `${'lastmod' in u ? `<lastmod>${u.lastmod}</lastmod>` : ''}`
        + `<priority>${u.pri}</priority></url>`).join('\n')
      + `\n</urlset>\n`,
    );
  })().catch(() => res.status(500).end());
});

// The storefront is plain files, so it is served straight from here — one
// process to run in development, and a CDN in front of /public in production.
app.use(express.static(join(ROOT, 'public'), { extensions: ['html'] }));

app.get('/api/business', (_req, res) => {
  // The seller's own details, which the law requires be published — unlike
  // data/sourcing.json, this one is meant to be public.
  res.json(business());
});

/**
 * Runtime settings for the storefront. The pages are static files, so this is
 * how anything environment-dependent reaches them without a build step.
 */
app.get('/config.js', (_req, res) => {
  const seller = business();
  res.type('application/javascript');
  res.setHeader('Cache-Control', 'no-cache');
  res.send(`window.__SHOP=${JSON.stringify({
    pixelId: config.metaPixelId,
    analytics: config.analytics,
    // The product page states these, the cart charges them and the footer
    // repeats them. Three hardcoded copies is three chances to disagree.
    freeShippingOver: config.freeShippingOver,
    shippingFlat: config.shippingFlat,
    // Delivery time is stated on the product page, in the footer and in the
    // delivery fold. One value from data/business.json reaches all three
    // rather than three strings that drift apart the first time it changes.
    deliveryMinDays: seller.deliveryMinDays,
    deliveryMaxDays: seller.deliveryMaxDays,
    // Drives the banner. While this is true the shop is showing numbers that
    // are not real, and it says so on every page rather than only in a log.
    demoData: demoData.present,
  })};`);
});

app.get('/api/health', (_req, res) => {
  res.json({ ok: true, driver: config.driver, currency: config.currency });
});

app.use('/api', catalogueRoutes(repo));
app.use('/api', orderRoutes(repo));
app.use('/api', analyticsRoutes(repo));
app.use('/api', reviewRoutes(repo));
app.use('/api/admin', adminRoutes(repo));

app.use('/api', (_req, res) => {
  res.status(404).json({ error: 'no such endpoint' });
});

/*
 * Anything else is a page that does not exist. Answered with the 404 page and a
 * 404 status — a soft 404 that returns the home page with a 200 is how a shop
 * ends up with a hundred duplicate pages in a search index.
 */
app.use((req, res, next) => {
  if (req.method !== 'GET' || req.path.startsWith('/api')) { next(); return; }
  res.status(404).type('html').sendFile(join(ROOT, 'public', '404.html'));
});

app.use((err: unknown, _req: express.Request, res: express.Response, _next: express.NextFunction) => {
  const status = err instanceof HttpError ? err.status : 500;
  const message = err instanceof Error ? err.message : 'unexpected error';
  if (status >= 500) console.error(err);
  res.status(status).json({ error: message });
});

app.listen(config.port, () => {
  console.log(`\n  oxide-jewelry`);
  console.log(`  storefront  http://localhost:${config.port}`);
  console.log(`  api         http://localhost:${config.port}/api/products`);
  const where = config.driver === 'json' ? 'data/products/, data/orders.json'
    : process.env.FIRESTORE_EMULATOR_HOST ? `emulator ${process.env.FIRESTORE_EMULATOR_HOST}`
    : process.env.GOOGLE_CLOUD_PROJECT || process.env.FIRESTORE_PROJECT_ID || 'no project set';
  console.log(`  store       ${config.driver} — ${where}`);
  if (config.driver === 'firestore' && where === 'no project set') {
    console.log(`  set GOOGLE_CLOUD_PROJECT, or FIRESTORE_EMULATOR_HOST for the emulator`);
  }

  console.log(`  stats       ${config.analytics ? 'on — data/analytics/, npm run stats' : 'off (ANALYTICS=off)'}`);
  if (config.adminToken) {
    console.log(`  admin       http://localhost:${config.port}/admin.html`);
  } else {
    /*
     * Closed is the right default, but a 404 with no explanation sends you
     * looking for a broken page instead of a missing variable. So say where
     * the admin page is, why it will not let you in, and exactly how to fix
     * it — the first time this was hit, the answer was one line of output away.
     */
    console.log(`  admin       /admin.html needs ADMIN_TOKEN — without it the admin API is 404`);
    // A token you can paste, rather than a command to go and find. Generated
    // fresh each boot and used nowhere until you save it, so printing it costs
    // nothing and removes the step where you go looking for openssl.
    console.log(`\n  echo 'ADMIN_TOKEN=${randomBytes(24).toString('hex')}' >> .env\n  then restart`);
  }

  if (demoData.present) {
    // console.log(`\n  DEMO DATA PRESENT — ${demoData.reviews} fabricated review(s), ${demoData.days} day(s) of traffic`);
    // console.log(`  The storefront is showing a banner. npm run demo -- --clear when you are done.`);
  }

  const gaps = unfilled();
  if (gaps.length) {
    console.log(`\n  data/business.json is unfilled: ${gaps.join(', ')}`);
    console.log(`  /privacy and /contact will show placeholders until it is.`);
    // Running ads to a destination with no published seller details is both a
    // Meta policy problem and a Consumer Protection (E-Commerce) Rules one.
    if (config.metaPixelId) {
      console.log(`  the Meta Pixel is ON while those pages are incomplete — fix before spending.`);
    }
  }
  console.log('');
});
